services:
  huh.filter.listener.dca.callback.filterconfigelement:
    class: HeimrichHannot\FilterBundle\EventListener\FilterConfigElementCallbackListener
  huh.filter.listener.inserttag:
    class: HeimrichHannot\FilterBundle\EventListener\InsertTagsListener
    arguments:
      - "@contao.framework"