services:
  _defaults:
    public: true
    autowire: true

  huh.filter.listener.dca.callback.filterconfigelement:
    class: HeimrichHannot\FilterBundle\EventListener\FilterConfigElementCallbackListener
  huh.filter.listener.hooks:
    class: HeimrichHannot\FilterBundle\EventListener\HookListener
  huh.filter.listener.inserttag:
    class: HeimrichHannot\FilterBundle\EventListener\InsertTagsListener
    arguments:
      - "@contao.framework"
