services:
  huh.filter.registry:
    class: HeimrichHannot\FilterBundle\Registry\FilterRegistry
    arguments:
        - "@contao.framework"
        - "@huh.filter.session"
  huh.filter.session:
      class: HeimrichHannot\FilterBundle\Entity\FilterSession
      arguments:
          - "@contao.framework"
          - "@session"
  huh.filter.config:
      class: HeimrichHannot\FilterBundle\Config\FilterConfig
      shared: false
  huh.filter.query_builder:
      class: HeimrichHannot\FilterBundle\QueryBuilder\FilterQueryBuilder
      arguments:
          - "@contao.framework"
          - "@doctrine.dbal.default_connection"
  huh.filter.choice.data_container:
      class: HeimrichHannot\FilterBundle\Choice\DataContainerChoice
      arguments:
        - "@contao.framework"
  huh.filter.choice.template:
      class: HeimrichHannot\FilterBundle\Choice\TemplateChoice
      arguments:
        - "@contao.framework"
  huh.filter.choice.parent:
      class: HeimrichHannot\FilterBundle\Choice\ParentChoice
      arguments:
        - "@contao.framework"
  huh.filter.choice.field:
      class: HeimrichHannot\FilterBundle\Choice\FieldChoice
      arguments:
        - "@contao.framework"
  huh.filter.choice.type:
      class: HeimrichHannot\FilterBundle\Choice\TypeChoice
      arguments:
          - "@contao.framework"
  huh.filter.choice.message:
      class: HeimrichHannot\FilterBundle\Choice\MessageChoice
      arguments:
          - "@contao.framework"
  huh.filter.choice.field_options:
      class: HeimrichHannot\FilterBundle\Choice\FieldOptionsChoice
      arguments:
        - "@contao.framework"