services:
  _defaults:
    public: true
    autowire: true

  huh.form_type_extension:
    class: HeimrichHannot\FilterBundle\Form\Extension\FormTypeExtension
    tags:
    - {name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType}

  huh.form_button_extension:
    class: HeimrichHannot\FilterBundle\Form\Extension\FormButtonExtension
    tags:
    - {name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType}

  huh.filter.manager:
    class: HeimrichHannot\FilterBundle\Manager\FilterManager
    public: true
    arguments:
    - "@contao.framework"
    - "@huh.filter.session"

  HeimrichHannot\FilterBundle\Manager\FilterManager:
    alias: 'huh.filter.manager'
    public: true

  huh.filter.session:
    class: HeimrichHannot\FilterBundle\Session\FilterSession
    public: true
    arguments:
    - "@contao.framework"
    - "@session"

  HeimrichHannot\FilterBundle\Session\FilterSession:
    alias: 'huh.filter.session'
    public: true

  huh.filter.config:
    class: HeimrichHannot\FilterBundle\Config\FilterConfig
    shared: false
    public: true
    arguments:
    - "@service_container"
    - "@contao.framework"
    - "@huh.filter.session"
    - "@doctrine.dbal.default_connection"
    - "@request_stack"

  huh.filter.backend.filter_config_element:
    public: true
    class: HeimrichHannot\FilterBundle\Backend\FilterConfigElement
    arguments:
    - "@contao.framework"

  huh.filter.backend.content:
    public: true
    class: HeimrichHannot\FilterBundle\Backend\Content
    arguments:
    - "@contao.framework"

  huh.filter.backend.filter_preselect:
    public: true
    class: HeimrichHannot\FilterBundle\Backend\FilterPreselect
    arguments:
    - "@contao.framework"

  # choices
  huh.filter.choice.template:
    class: HeimrichHannot\FilterBundle\Choice\TemplateChoice
    public: true
    arguments:
    - "@contao.framework"

  HeimrichHannot\FilterBundle\Choice\TypeChoice: ~
  huh.filter.choice.type: '@HeimrichHannot\FilterBundle\Choice\TypeChoice'
#    class: HeimrichHannot\FilterBundle\Choice\TypeChoice
#    public: true
#    arguments:
#    - "@contao.framework"

  huh.filter.choice.field_options:
    class: HeimrichHannot\FilterBundle\Choice\FieldOptionsChoice
    public: true
    arguments:
    - "@contao.framework"

  huh.filter.choice.country:
    class: HeimrichHannot\FilterBundle\Choice\CountryChoice
    public: true
    arguments:
    - "@contao.framework"

  huh.filter.choice.date:
    class: HeimrichHannot\FilterBundle\Choice\DateChoice
    public: true
    arguments: ['@contao.framework', '@huh.utils.model']

  huh.filter.choice.language:
    class: HeimrichHannot\FilterBundle\Choice\LanguageChoice
    public: true
    arguments:
    - "@contao.framework"

  huh.filter.choice.locale:
    class: HeimrichHannot\FilterBundle\Choice\LocaleChoice
    public: true
    arguments:
    - "@contao.framework"

  huh.filter.choice.element:
    class: HeimrichHannot\FilterBundle\Choice\ElementChoice
    public: true
    arguments:
    - "@contao.framework"

  huh.filter.choice.year:
    class: HeimrichHannot\FilterBundle\Choice\YearChoice
    public: true
    arguments: ['@service_container', '@huh.utils.model']

  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
    - { name: twig.extension }

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
    - { name: twig.extension }

  twig.extension.array:
    class: Twig_Extensions_Extension_Array
    tags:
    - { name: twig.extension }

  twig.extension.date:
    class: Twig_Extensions_Extension_Date
    arguments:
    - "@translator"
    tags:
    - { name: twig.extension }

  huh.filter.choice.sort:
    class: HeimrichHannot\FilterBundle\Choice\SortChoice
    public: true
    arguments:
    - "@contao.framework"

  huh.filter.util.filter_config_element:
    class: HeimrichHannot\FilterBundle\Util\FilterConfigElementUtil
    public: true
    arguments:
    - "@contao.framework"

  huh.filter.util.filter_preselect:
    class: HeimrichHannot\FilterBundle\Util\FilterPreselectUtil
    public: true
    arguments:
    - "@contao.framework"
  HeimrichHannot\FilterBundle\Util\FilterPreselectUtil: '@huh.filter.util.filter_preselect'

  huh.filter.util.filter_ajax:
    class: HeimrichHannot\FilterBundle\Util\FilterAjaxUtil
    public: true
    autowire: true

  twig.truncate.service:
    class: Urodoz\Truncate\TruncateService

  twig.extension.truncate.html:
    class: Urodoz\Truncate\Bridge\Twig\TruncateExtension
    arguments:
    - "@twig.truncate.service"
    tags:
    - { name: twig.extension }

  HeimrichHannot\FilterBundle\FilterType\Type\TextType: ~
  HeimrichHannot\FilterBundle\Filter\Filter: ~

  huh.filter.filter_type_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: ['container.service_locator']
    arguments:
      - 'textType': '@HeimrichHannot\FilterBundle\FilterType\Type\TextType'