services:
  huh.filter.registry:
    class: HeimrichHannot\FilterBundle\Registry\FilterRegistry
    arguments:
        - "@contao.framework"
  huh.filter.config:
      class: HeimrichHannot\FilterBundle\Config\FilterConfig
      arguments:
          - "@contao.framework"
  huh.filter.choice.data_container:
      class: HeimrichHannot\FilterBundle\Choice\DataContainerChoice
      arguments:
        - "@contao.framework"
  huh.filter.choice.template:
      class: HeimrichHannot\FilterBundle\Choice\TemplateChoice
      arguments:
        - "@contao.framework"
  huh.filter.choice.parent:
      class: HeimrichHannot\FilterBundle\Choice\ParentChoice
      arguments:
        - "@contao.framework"
  huh.filter.choice.field:
      class: HeimrichHannot\FilterBundle\Choice\FieldChoice
      arguments:
        - "@contao.framework"
  huh.filter.choice.type:
      class: HeimrichHannot\FilterBundle\Choice\TypeChoice
      arguments:
          - "@contao.framework"
  huh.filter.choice.message:
      class: HeimrichHannot\FilterBundle\Choice\MessageChoice
      arguments:
          - "@contao.framework"