services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true
    bind:
      $bundleConfig: '%huh.filter%'

  HeimrichHannot\FilterBundle\:
    resource: '../../{Asset,Choice,Controller,DataContainer,EventListener,Util}/*'
    exclude: '../../EventListener/{FilterConfigElementCallbackListener.php,HookListener.php,InsertTagsListener.php}'
    autoconfigure: true
    autowire: true
    public: false

  HeimrichHannot\FilterBundle\Filter\FilterCollection:
    autowire: true
    public: true

  huh.form_type_extension:
    class: HeimrichHannot\FilterBundle\Form\Extension\FormTypeExtension
    tags:
    - {name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType}

  huh.form_button_extension:
    class: HeimrichHannot\FilterBundle\Form\Extension\FormButtonExtension
    tags:
    - {name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType}

  huh.filter.manager:
    class: HeimrichHannot\FilterBundle\Manager\FilterManager
    public: true

  HeimrichHannot\FilterBundle\Manager\FilterManager:
    alias: 'huh.filter.manager'
    public: true

  huh.filter.session:
    class: HeimrichHannot\FilterBundle\Session\FilterSession
    public: true

  HeimrichHannot\FilterBundle\Session\FilterSession:
    alias: 'huh.filter.session'
    public: true

  huh.filter.config:
    class: HeimrichHannot\FilterBundle\Config\FilterConfig
    shared: false
    public: true

  HeimrichHannot\FilterBundle\Config\FilterConfig: "@huh.filter.config"

  huh.filter.backend.filter_config_element:
    public: true
    class: HeimrichHannot\FilterBundle\Backend\FilterConfigElement
    autowire: true

  huh.filter.backend.filter_preselect:
    public: true
    class: HeimrichHannot\FilterBundle\Backend\FilterPreselect
    autowire: true

  # choices
  huh.filter.choice.template:
    class: HeimrichHannot\FilterBundle\Choice\TemplateChoice
    public: true

  huh.filter.choice.type:
    class: HeimrichHannot\FilterBundle\Choice\TypeChoice
    public: true

  HeimrichHannot\FilterBundle\Choice\FieldOptionsChoice: ~
  huh.filter.choice.field_options: '@HeimrichHannot\FilterBundle\Choice\FieldOptionsChoice'

  huh.filter.choice.country:
    deprecated:
        message: 'The "%service_id%" service is deprecated. Use HeimrichHannot\FilterBundle\Choice\FilterChoices::getCountryOptions instead.'
        package: heimrichhannot/contao-filter-bundle
        version: '<2.0.0'
    public: true
    synthetic: true

  huh.filter.choice.date:
    class: HeimrichHannot\FilterBundle\Choice\DateChoice
    public: true

  huh.filter.choice.language:
    class: HeimrichHannot\FilterBundle\Choice\LanguageChoice
    public: true

  huh.filter.choice.locale:
    class: HeimrichHannot\FilterBundle\Choice\LocaleChoice
    public: true

  huh.filter.choice.element:
    deprecated:
        message: 'The "%service_id%" service is deprecated. Use HeimrichHannot\FilterBundle\Choice\FilterChoices::getElementOptions instead.'
        package: heimrichhannot/contao-filter-bundle
        version: '<2.0.0'
    public: true
    synthetic: true

  huh.filter.choice.year:
    class: HeimrichHannot\FilterBundle\Choice\YearChoice
    public: true

  huh.filter.choice.sort:
    class: HeimrichHannot\FilterBundle\Choice\SortChoice
    public: true

  huh.filter.util.filter_config_element:
    class: HeimrichHannot\FilterBundle\Util\FilterConfigElementUtil
    public: true

  huh.filter.util.filter_preselect:
    class: HeimrichHannot\FilterBundle\Util\FilterPreselectUtil
    public: true

  HeimrichHannot\FilterBundle\Util\FilterPreselectUtil: '@huh.filter.util.filter_preselect'

  huh.filter.util.filter_ajax:
    class: HeimrichHannot\FilterBundle\Util\FilterAjaxUtil
    public: true
    autowire: true

  # twig.truncate.service:
  #   class: Urodoz\Truncate\TruncateService

  # twig.extension.truncate.html:
  #   class: Urodoz\Truncate\Bridge\Twig\TruncateExtension
  #   arguments:
  #   - "@twig.truncate.service"
  #   tags:
  #   - { name: twig.extension }

  twig.extension.string:
    class: Twig\Extra\String\StringExtension
    autowire: true
    tags:
      - { name: twig.extension }

  twig.extension.html:
    class: Twig\Extra\Html\HtmlExtension
    autowire: true
    tags:
      - { name: twig.extension }

  twig.extension.intl:
    class: Twig\Extra\Intl\IntlExtension
    autowire: true
    tags:
      - { name: twig.extension }
